### PR TITLE
Adding random seed for crimson kimono

### PR DESCRIPTION
**Pull request by Zeisenx**
Crimson Kimono has some pattern like full-red, full red only right hand, and left hand.

that pattern depends on seed so I made it works.

image

### CODE REVIEW

**Comment by crashzk** [comment]
@Zeisenx Interesting, enjoy.

But would it be possible to also put the option for the player to choose the seed? Like Weapons & Knives, the command `!seed` in this case.

**Comment by Zeisenx** [comment]
> @Zeisenx Interesting, enjoy.
> 
> But would it be possible to also put the option for the player to choose the seed? Like Weapons & Knives, the command `!seed` in this case.

It will be cool. I'll commit when I have work time on it.

**Comment by crashzk** [comment]
> > @Zeisenx Interesting, enjoy.
> > But would it be possible to also put the option for the player to choose the seed? Like Weapons & Knives, the command `!seed` in this case.
> 
> It will be cool. I'll commit when I have work time on it.

Perfect, I'll be waiting, thanks.

And I would also like to take the opportunity to report a BUG.

I updated my version based on your modifications, and this generates an error in the server:
```
L 12/07/2020 - 08:45:09: [SM] Exception reported: SendProp m_nFallbackSeed type is not float (0 != 1)
L 12/07/2020 - 08:45:09: [SM] Blaming: gloves.smx
L 12/07/2020 - 08:45:09: [SM] Call stack trace:
L 12/07/2020 - 08:45:09: [SM]   [0] SetEntPropFloat
L 12/07/2020 - 08:45:09: [SM]   [1] Line 170, C:\Users\boy-l\Google Drive\ZK Servidores™\Servidores\Counter-Strike Global Offensive\Editar Plugins\addons SM1.10\sourcemod\scripting\gloves.sp::GivePlayerGloves
L 12/07/2020 - 08:45:09: [SM]   [2] Line 23, gloves/hooks.sp::Event_PlayerSpawn
L 12/07/2020 - 08:45:10: [SM] Exception reported: SendProp m_nFallbackSeed type is not float (0 != 1)
L 12/07/2020 - 08:45:10: [SM] Blaming: gloves.smx
L 12/07/2020 - 08:45:10: [SM] Call stack trace:
L 12/07/2020 - 08:45:10: [SM]   [0] SetEntPropFloat
L 12/07/2020 - 08:45:10: [SM]   [1] Line 170, C:\Users\boy-l\Google Drive\ZK Servidores™\Servidores\Counter-Strike Global Offensive\Editar Plugins\addons SM1.10\sourcemod\scripting\gloves.sp::GivePlayerGloves
L 12/07/2020 - 08:45:10: [SM]   [2] Line 23, gloves/hooks.sp::Event_PlayerSpawn
L 12/07/2020 - 08:45:10: [SM]   [4] CS_RespawnPlayer
L 12/07/2020 - 08:45:10: [SM]   [5] Line 7751, C:\Users\boy-l\Google Drive\ZK Servidores™\Servidores\Counter-Strike Global Offensive\Editar Plugins\addons SM1.10\sourcemod\scripting\warmod.sp::RespawnPlayer
L 12/07/2020 - 08:45:10: [SM] Exception reported: SendProp m_nFallbackSeed type is not float (0 != 1)
L 12/07/2020 - 08:45:10: [SM] Blaming: gloves.smx
L 12/07/2020 - 08:45:10: [SM] Call stack trace:
L 12/07/2020 - 08:45:10: [SM]   [0] SetEntPropFloat
L 12/07/2020 - 08:45:10: [SM]   [1] Line 170, C:\Users\boy-l\Google Drive\ZK Servidores™\Servidores\Counter-Strike Global Offensive\Editar Plugins\addons SM1.10\sourcemod\scripting\gloves.sp::GivePlayerGloves
L 12/07/2020 - 08:45:10: [SM]   [2] Line 23, gloves/hooks.sp::Event_PlayerSpawn
L 12/07/2020 - 08:45:10: [SM]   [4] CS_RespawnPlayer
L 12/07/2020 - 08:45:10: [SM]   [5] Line 7751, C:\Users\boy-l\Google Drive\ZK Servidores™\Servidores\Counter-Strike Global Offensive\Editar Plugins\addons SM1.10\sourcemod\scripting\warmod.sp::RespawnPlayer
L 12/07/2020 - 08:47:02: [SM] Exception reported: SendProp m_nFallbackSeed type is not float (0 != 1)
L 12/07/2020 - 08:47:02: [SM] Blaming: gloves.smx
L 12/07/2020 - 08:47:02: [SM] Call stack trace:
L 12/07/2020 - 08:47:02: [SM]   [0] SetEntPropFloat
L 12/07/2020 - 08:47:02: [SM]   [1] Line 170, C:\Users\boy-l\Google Drive\ZK Servidores™\Servidores\Counter-Strike Global Offensive\Editar Plugins\addons SM1.10\sourcemod\scripting\gloves.sp::GivePlayerGloves
L 12/07/2020 - 08:47:02: [SM]   [2] Line 160, gloves/menus.sp::GloveMainMenuHandler
L 12/07/2020 - 08:47:16: [SM] Exception reported: SendProp m_nFallbackSeed type is not float (0 != 1)
L 12/07/2020 - 08:47:16: [SM] Blaming: gloves.smx
L 12/07/2020 - 08:47:16: [SM] Call stack trace:
L 12/07/2020 - 08:47:16: [SM]   [0] SetEntPropFloat
L 12/07/2020 - 08:47:16: [SM]   [1] Line 170, C:\Users\boy-l\Google Drive\ZK Servidores™\Servidores\Counter-Strike Global Offensive\Editar Plugins\addons SM1.10\sourcemod\scripting\gloves.sp::GivePlayerGloves
L 12/07/2020 - 08:47:16: [SM]   [2] Line 57, gloves/menus.sp::GloveMenuHandler
```
In case the gloves are not applied, it is invisible.
image

**Comment by Zeisenx** [comment]
Damn my typo. Fixed now.

**Comment by crashzk** [comment]
@Zeisenx It worked, even though I don't sell this random seed in the crimson kimono... :) I'll be seeing better to see if the seed really changes.

Could you tell me how this function even works? Is each round a random seed for gloves? Any way to apply this random seed to all gloves, I believe it has it for everyone, right?

**Comment by Zeisenx** [comment]
> Could you tell me how this function even works?

That gives random seed to gloves when it is generated. Simple.

> Any way to apply this random seed to all gloves, I believe it has it for everyone, right?

Yes.

**Comment by crashzk** [comment]
Moving on to leave feedback, so far everything is fine with this feature.

@kgns I believe it can be merged with the project, but I believe that in the future, as I mentioned, it would be nice to be able to choose a seed, just like **weapons.smx.**

**Comment by kgns** [comment]
Sorry for the late response, I've been away from CS:GO for a while. This seems like a simple enhancement that would benefit some players. Thanks for the PR

**Pull request merged**
